// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/obase/go/api/base.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Body int32

const (
	Body_JSON Body = 0
	Body_FORM Body = 1
)

var Body_name = map[int32]string{
	0: "JSON",
	1: "FORM",
}

var Body_value = map[string]int32{
	"JSON": 0,
	"FORM": 1,
}

func (x Body) String() string {
	return proto.EnumName(Body_name, int32(x))
}

func (Body) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8fa6c8035c3d80ff, []int{0}
}

type PackFunc struct {
	Pack                 string   `protobuf:"bytes,1,opt,name=pack,proto3" json:"pack,omitempty" bson:"pack"`
	Func                 string   `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty" bson:"func"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PackFunc) Reset()         { *m = PackFunc{} }
func (m *PackFunc) String() string { return proto.CompactTextString(m) }
func (*PackFunc) ProtoMessage()    {}
func (*PackFunc) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fa6c8035c3d80ff, []int{0}
}

func (m *PackFunc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackFunc.Unmarshal(m, b)
}
func (m *PackFunc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackFunc.Marshal(b, m, deterministic)
}
func (m *PackFunc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackFunc.Merge(m, src)
}
func (m *PackFunc) XXX_Size() int {
	return xxx_messageInfo_PackFunc.Size(m)
}
func (m *PackFunc) XXX_DiscardUnknown() {
	xxx_messageInfo_PackFunc.DiscardUnknown(m)
}

var xxx_messageInfo_PackFunc proto.InternalMessageInfo

func (m *PackFunc) GetPack() string {
	if m != nil {
		return m.Pack
	}
	return ""
}

func (m *PackFunc) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type Group struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty" bson:"path"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty" bson:"desc"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fa6c8035c3d80ff, []int{1}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Group) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Handle struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty" bson:"path"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty" bson:"desc"`
	Body                 Body     `protobuf:"varint,3,opt,name=body,proto3,enum=api.Body" json:"body,omitempty" bson:"body"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Handle) Reset()         { *m = Handle{} }
func (m *Handle) String() string { return proto.CompactTextString(m) }
func (*Handle) ProtoMessage()    {}
func (*Handle) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fa6c8035c3d80ff, []int{2}
}

func (m *Handle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handle.Unmarshal(m, b)
}
func (m *Handle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handle.Marshal(b, m, deterministic)
}
func (m *Handle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handle.Merge(m, src)
}
func (m *Handle) XXX_Size() int {
	return xxx_messageInfo_Handle.Size(m)
}
func (m *Handle) XXX_DiscardUnknown() {
	xxx_messageInfo_Handle.DiscardUnknown(m)
}

var xxx_messageInfo_Handle proto.InternalMessageInfo

func (m *Handle) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Handle) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Handle) GetBody() Body {
	if m != nil {
		return m.Body
	}
	return Body_JSON
}

type Socket struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty" bson:"path"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty" bson:"desc"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Socket) Reset()         { *m = Socket{} }
func (m *Socket) String() string { return proto.CompactTextString(m) }
func (*Socket) ProtoMessage()    {}
func (*Socket) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fa6c8035c3d80ff, []int{3}
}

func (m *Socket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Socket.Unmarshal(m, b)
}
func (m *Socket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Socket.Marshal(b, m, deterministic)
}
func (m *Socket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Socket.Merge(m, src)
}
func (m *Socket) XXX_Size() int {
	return xxx_messageInfo_Socket.Size(m)
}
func (m *Socket) XXX_DiscardUnknown() {
	xxx_messageInfo_Socket.DiscardUnknown(m)
}

var xxx_messageInfo_Socket proto.InternalMessageInfo

func (m *Socket) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Socket) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Field struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty" bson:"json"`
	Bson                 string   `protobuf:"bytes,2,opt,name=bson,proto3" json:"bson,omitempty" bson:"bson"`
	File                 bool     `protobuf:"varint,3,opt,name=file,proto3" json:"file,omitempty" bson:"file"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fa6c8035c3d80ff, []int{4}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *Field) GetBson() string {
	if m != nil {
		return m.Bson
	}
	return ""
}

func (m *Field) GetFile() bool {
	if m != nil {
		return m.File
	}
	return false
}

var E_ServerOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90001,
	Name:          "api.server_option",
	Tag:           "bytes,90001,rep,name=server_option",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_MiddleFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90002,
	Name:          "api.middle_filter",
	Tag:           "bytes,90002,rep,name=middle_filter",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         90001,
	Name:          "api.field",
	Tag:           "bytes,90001,opt,name=field",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_Group = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*Group)(nil),
	Field:         90001,
	Name:          "api.group",
	Tag:           "bytes,90001,opt,name=group",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_GroupFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90002,
	Name:          "api.group_filter",
	Tag:           "bytes,90002,rep,name=group_filter",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_Handle = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Handle)(nil),
	Field:         90001,
	Name:          "api.handle",
	Tag:           "bytes,90001,opt,name=handle",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_HandleFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90002,
	Name:          "api.handle_filter",
	Tag:           "bytes,90002,rep,name=handle_filter",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_Socket = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Socket)(nil),
	Field:         90003,
	Name:          "api.socket",
	Tag:           "bytes,90003,opt,name=socket",
	Filename:      "github.com/obase/go/api/base.proto",
}

var E_SocketFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90004,
	Name:          "api.socket_filter",
	Tag:           "bytes,90004,rep,name=socket_filter",
	Filename:      "github.com/obase/go/api/base.proto",
}

func init() {
	proto.RegisterEnum("api.Body", Body_name, Body_value)
	proto.RegisterType((*PackFunc)(nil), "api.PackFunc")
	proto.RegisterType((*Group)(nil), "api.Group")
	proto.RegisterType((*Handle)(nil), "api.Handle")
	proto.RegisterType((*Socket)(nil), "api.Socket")
	proto.RegisterType((*Field)(nil), "api.Field")
	proto.RegisterExtension(E_ServerOption)
	proto.RegisterExtension(E_MiddleFilter)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Group)
	proto.RegisterExtension(E_GroupFilter)
	proto.RegisterExtension(E_Handle)
	proto.RegisterExtension(E_HandleFilter)
	proto.RegisterExtension(E_Socket)
	proto.RegisterExtension(E_SocketFilter)
}

func init() { proto.RegisterFile("github.com/obase/go/api/base.proto", fileDescriptor_8fa6c8035c3d80ff) }

var fileDescriptor_8fa6c8035c3d80ff = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0x31, 0x89, 0xa3, 0xf4, 0xa6, 0x41, 0x95, 0x57, 0x51, 0x45, 0x21, 0xf2, 0x2a, 0x62,
	0x61, 0xa3, 0xb0, 0xf3, 0x0e, 0x2a, 0x0c, 0x42, 0x2a, 0x41, 0x13, 0xf6, 0x95, 0x7f, 0xc6, 0xf6,
	0x10, 0xd7, 0x63, 0x8d, 0xc7, 0x95, 0xfa, 0x18, 0xfc, 0xbc, 0x0f, 0xaf, 0x86, 0xe6, 0x5e, 0x5b,
	0xa5, 0x4a, 0x22, 0x67, 0x77, 0x74, 0xc6, 0xe7, 0xf3, 0xb9, 0x33, 0x17, 0xdc, 0x5c, 0xe8, 0xa2,
	0x8d, 0xbd, 0x44, 0xde, 0xf9, 0x32, 0x8e, 0x1a, 0xee, 0xe7, 0xd2, 0x8f, 0x6a, 0xe1, 0x1b, 0xed,
	0xd5, 0x4a, 0x6a, 0xe9, 0x8c, 0xa2, 0x5a, 0x5c, 0x2e, 0x73, 0x29, 0xf3, 0x92, 0xfb, 0x68, 0xc5,
	0x6d, 0xe6, 0xa7, 0xbc, 0x49, 0x94, 0xa8, 0xb5, 0x54, 0xf4, 0x99, 0xbb, 0x86, 0xe9, 0xb7, 0x28,
	0xd9, 0x85, 0x6d, 0x95, 0x38, 0x0e, 0x8c, 0xeb, 0x28, 0xd9, 0x2d, 0xac, 0xa5, 0xb5, 0x3a, 0x63,
	0xa8, 0x8d, 0x97, 0xb5, 0x55, 0xb2, 0x78, 0x4e, 0x9e, 0xd1, 0xae, 0x0f, 0xf6, 0x27, 0x25, 0xdb,
	0x9a, 0x02, 0xba, 0x78, 0x0c, 0xe8, 0xc2, 0x78, 0xe6, 0x27, 0x7d, 0xc0, 0x68, 0x77, 0x03, 0x93,
	0xcf, 0x51, 0x95, 0x96, 0xfc, 0xd4, 0x84, 0x73, 0x05, 0xe3, 0x58, 0xa6, 0x0f, 0x8b, 0xd1, 0xd2,
	0x5a, 0xbd, 0x58, 0x9f, 0x79, 0x51, 0x2d, 0xbc, 0x0f, 0x32, 0x7d, 0x60, 0x68, 0xbb, 0x6f, 0x61,
	0xb2, 0x95, 0xc9, 0x8e, 0xeb, 0x93, 0x2b, 0x5c, 0x83, 0x1d, 0x0a, 0x5e, 0xa6, 0xe6, 0xf0, 0x47,
	0x23, 0xab, 0x3e, 0x60, 0xb4, 0xf1, 0x62, 0xe3, 0x75, 0x81, 0xb8, 0xf3, 0x32, 0x51, 0x72, 0x6c,
	0x30, 0x65, 0xa8, 0xdf, 0x5c, 0xc2, 0xd8, 0x94, 0x70, 0xa6, 0x30, 0xfe, 0xb2, 0xdd, 0x7c, 0xbd,
	0x78, 0x66, 0x54, 0xb8, 0x61, 0x37, 0x17, 0x56, 0xc0, 0x60, 0xde, 0x70, 0x75, 0xcf, 0xd5, 0xad,
	0xac, 0xb5, 0x90, 0x95, 0xf3, 0xd2, 0xa3, 0xcb, 0xf7, 0xfa, 0xcb, 0xf7, 0x42, 0x51, 0xf2, 0x0d,
	0x1e, 0x36, 0x8b, 0x9f, 0x7f, 0xed, 0xe5, 0x68, 0x35, 0x5b, 0xcf, 0x71, 0xb4, 0xfe, 0x09, 0xd8,
	0x39, 0x31, 0xe8, 0x2b, 0xc3, 0xbc, 0x13, 0x69, 0x5a, 0xf2, 0xdb, 0x4c, 0x94, 0x9a, 0xab, 0x01,
	0xe6, 0xaf, 0x23, 0x4c, 0x62, 0x84, 0x88, 0x08, 0xde, 0x83, 0x9d, 0xe1, 0x45, 0x5c, 0x1d, 0x60,
	0xf1, 0x32, 0xfd, 0xbf, 0xa0, 0xb5, 0x9a, 0xad, 0x01, 0x61, 0x78, 0xc4, 0x28, 0x19, 0x5c, 0x83,
	0x9d, 0xe3, 0xfb, 0xbf, 0xde, 0x43, 0x6c, 0xb9, 0xba, 0x17, 0x09, 0x3f, 0x0c, 0xc1, 0xa5, 0x61,
	0x94, 0x0d, 0xb6, 0x70, 0x8e, 0xa2, 0x1f, 0x6d, 0x90, 0x75, 0x64, 0xba, 0x19, 0x52, 0xba, 0xe1,
	0x3e, 0xc2, 0xa4, 0xa0, 0x45, 0x7b, 0xb5, 0x87, 0xbb, 0xe1, 0xba, 0x90, 0x7b, 0xe3, 0xcd, 0x90,
	0x46, 0xdb, 0xc9, 0xba, 0x70, 0xf0, 0x1d, 0xe6, 0xa4, 0xfa, 0x72, 0x43, 0xb4, 0x63, 0x37, 0x4f,
	0x94, 0xc7, 0x72, 0x0d, 0x2d, 0xed, 0x10, 0xee, 0xf7, 0x93, 0x72, 0xb4, 0xe9, 0xac, 0x0b, 0x9b,
	0x72, 0xa4, 0x4e, 0x2d, 0xf7, 0xe7, 0xd8, 0xaa, 0x21, 0x85, 0xca, 0xc5, 0x13, 0x0c, 0xbf, 0xfb,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x34, 0x70, 0x55, 0xb4, 0x5b, 0x04, 0x00, 0x00,
}
