// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/obase/api/x.proto

package x

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Body int32

const (
	Body_JSON Body = 0
	Body_FORM Body = 1
)

var Body_name = map[int32]string{
	0: "JSON",
	1: "FORM",
}

var Body_value = map[string]int32{
	"JSON": 0,
	"FORM": 1,
}

func (x Body) String() string {
	return proto.EnumName(Body_name, int32(x))
}

func (Body) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e7c1a25b3c76cdf, []int{0}
}

type PackFunc struct {
	Pack                 string   `protobuf:"bytes,1,opt,name=pack,proto3" json:"pack,omitempty"`
	Func                 string   `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackFunc) Reset()         { *m = PackFunc{} }
func (m *PackFunc) String() string { return proto.CompactTextString(m) }
func (*PackFunc) ProtoMessage()    {}
func (*PackFunc) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7c1a25b3c76cdf, []int{0}
}

func (m *PackFunc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackFunc.Unmarshal(m, b)
}
func (m *PackFunc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackFunc.Marshal(b, m, deterministic)
}
func (m *PackFunc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackFunc.Merge(m, src)
}
func (m *PackFunc) XXX_Size() int {
	return xxx_messageInfo_PackFunc.Size(m)
}
func (m *PackFunc) XXX_DiscardUnknown() {
	xxx_messageInfo_PackFunc.DiscardUnknown(m)
}

var xxx_messageInfo_PackFunc proto.InternalMessageInfo

func (m *PackFunc) GetPack() string {
	if m != nil {
		return m.Pack
	}
	return ""
}

func (m *PackFunc) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

type Group struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7c1a25b3c76cdf, []int{1}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Group) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Handle struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Body                 Body     `protobuf:"varint,3,opt,name=body,proto3,enum=api.Body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handle) Reset()         { *m = Handle{} }
func (m *Handle) String() string { return proto.CompactTextString(m) }
func (*Handle) ProtoMessage()    {}
func (*Handle) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7c1a25b3c76cdf, []int{2}
}

func (m *Handle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handle.Unmarshal(m, b)
}
func (m *Handle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handle.Marshal(b, m, deterministic)
}
func (m *Handle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handle.Merge(m, src)
}
func (m *Handle) XXX_Size() int {
	return xxx_messageInfo_Handle.Size(m)
}
func (m *Handle) XXX_DiscardUnknown() {
	xxx_messageInfo_Handle.DiscardUnknown(m)
}

var xxx_messageInfo_Handle proto.InternalMessageInfo

func (m *Handle) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Handle) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Handle) GetBody() Body {
	if m != nil {
		return m.Body
	}
	return Body_JSON
}

type Socket struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Socket) Reset()         { *m = Socket{} }
func (m *Socket) String() string { return proto.CompactTextString(m) }
func (*Socket) ProtoMessage()    {}
func (*Socket) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7c1a25b3c76cdf, []int{3}
}

func (m *Socket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Socket.Unmarshal(m, b)
}
func (m *Socket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Socket.Marshal(b, m, deterministic)
}
func (m *Socket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Socket.Merge(m, src)
}
func (m *Socket) XXX_Size() int {
	return xxx_messageInfo_Socket.Size(m)
}
func (m *Socket) XXX_DiscardUnknown() {
	xxx_messageInfo_Socket.DiscardUnknown(m)
}

var xxx_messageInfo_Socket proto.InternalMessageInfo

func (m *Socket) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Socket) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type Field struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Bson                 string   `protobuf:"bytes,2,opt,name=bson,proto3" json:"bson,omitempty"`
	File                 bool     `protobuf:"varint,3,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7c1a25b3c76cdf, []int{4}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *Field) GetBson() string {
	if m != nil {
		return m.Bson
	}
	return ""
}

func (m *Field) GetFile() bool {
	if m != nil {
		return m.File
	}
	return false
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e7c1a25b3c76cdf, []int{5}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

var E_ServerOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90001,
	Name:          "api.server_option",
	Tag:           "bytes,90001,rep,name=server_option",
	Filename:      "github.com/obase/api/x.proto",
}

var E_MiddleFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90002,
	Name:          "api.middle_filter",
	Tag:           "bytes,90002,rep,name=middle_filter",
	Filename:      "github.com/obase/api/x.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         90001,
	Name:          "api.field",
	Tag:           "bytes,90001,opt,name=field",
	Filename:      "github.com/obase/api/x.proto",
}

var E_Group = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*Group)(nil),
	Field:         90001,
	Name:          "api.group",
	Tag:           "bytes,90001,opt,name=group",
	Filename:      "github.com/obase/api/x.proto",
}

var E_GroupFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90002,
	Name:          "api.group_filter",
	Tag:           "bytes,90002,rep,name=group_filter",
	Filename:      "github.com/obase/api/x.proto",
}

var E_Handle = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Handle)(nil),
	Field:         90001,
	Name:          "api.handle",
	Tag:           "bytes,90001,opt,name=handle",
	Filename:      "github.com/obase/api/x.proto",
}

var E_HandleFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90002,
	Name:          "api.handle_filter",
	Tag:           "bytes,90002,rep,name=handle_filter",
	Filename:      "github.com/obase/api/x.proto",
}

var E_Socket = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Socket)(nil),
	Field:         90003,
	Name:          "api.socket",
	Tag:           "bytes,90003,opt,name=socket",
	Filename:      "github.com/obase/api/x.proto",
}

var E_SocketFilter = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: ([]*PackFunc)(nil),
	Field:         90004,
	Name:          "api.socket_filter",
	Tag:           "bytes,90004,rep,name=socket_filter",
	Filename:      "github.com/obase/api/x.proto",
}

func init() {
	proto.RegisterEnum("api.Body", Body_name, Body_value)
	proto.RegisterType((*PackFunc)(nil), "api.PackFunc")
	proto.RegisterType((*Group)(nil), "api.Group")
	proto.RegisterType((*Handle)(nil), "api.Handle")
	proto.RegisterType((*Socket)(nil), "api.Socket")
	proto.RegisterType((*Field)(nil), "api.Field")
	proto.RegisterType((*Void)(nil), "api.void")
	proto.RegisterExtension(E_ServerOption)
	proto.RegisterExtension(E_MiddleFilter)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Group)
	proto.RegisterExtension(E_GroupFilter)
	proto.RegisterExtension(E_Handle)
	proto.RegisterExtension(E_HandleFilter)
	proto.RegisterExtension(E_Socket)
	proto.RegisterExtension(E_SocketFilter)
}

func init() { proto.RegisterFile("github.com/obase/api/x.proto", fileDescriptor_5e7c1a25b3c76cdf) }

var fileDescriptor_5e7c1a25b3c76cdf = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x8f, 0x93, 0x40,
	0x18, 0xc6, 0xc5, 0x02, 0xe9, 0xbe, 0xdd, 0x9a, 0x0d, 0x07, 0x43, 0x36, 0xbb, 0xda, 0x70, 0x6a,
	0x3c, 0x80, 0xa9, 0x37, 0x6e, 0xee, 0x46, 0x34, 0x26, 0x6b, 0xcd, 0xd4, 0x93, 0x97, 0x0d, 0x30,
	0x43, 0x19, 0xcb, 0x32, 0x04, 0x86, 0xc6, 0xfd, 0x18, 0xfe, 0xf9, 0x3e, 0x7e, 0x35, 0x33, 0xef,
	0x40, 0xaa, 0x69, 0x1b, 0x7a, 0x7b, 0xf2, 0x0c, 0xcf, 0xaf, 0xcf, 0x3b, 0xf3, 0xa6, 0x70, 0xb5,
	0xe6, 0x32, 0x6f, 0x13, 0x3f, 0x15, 0x0f, 0x81, 0x48, 0xe2, 0x86, 0x05, 0x71, 0xc5, 0x83, 0xef,
	0x7e, 0x55, 0x0b, 0x29, 0x9c, 0x51, 0x5c, 0xf1, 0xcb, 0xd9, 0x5a, 0x88, 0x75, 0xc1, 0x02, 0xb4,
	0x92, 0x36, 0x0b, 0x28, 0x6b, 0xd2, 0x9a, 0x57, 0x52, 0xd4, 0xfa, 0x33, 0x6f, 0x01, 0xe3, 0xcf,
	0x71, 0xba, 0x89, 0xda, 0x32, 0x75, 0x1c, 0x30, 0xab, 0x38, 0xdd, 0xb8, 0xc6, 0xcc, 0x98, 0x9f,
	0x11, 0xd4, 0xca, 0xcb, 0xda, 0x32, 0x75, 0x9f, 0x6a, 0x4f, 0x69, 0x2f, 0x00, 0xeb, 0x7d, 0x2d,
	0xda, 0x4a, 0x07, 0x64, 0xbe, 0x0b, 0xc8, 0x5c, 0x79, 0xea, 0x47, 0xfa, 0x80, 0xd2, 0xde, 0x12,
	0xec, 0x0f, 0x71, 0x49, 0x0b, 0x76, 0x6a, 0xc2, 0xb9, 0x06, 0x33, 0x11, 0xf4, 0xd1, 0x1d, 0xcd,
	0x8c, 0xf9, 0xb3, 0xc5, 0x99, 0x1f, 0x57, 0xdc, 0xbf, 0x11, 0xf4, 0x91, 0xa0, 0xed, 0xbd, 0x06,
	0x7b, 0x25, 0xd2, 0x0d, 0x93, 0x27, 0x57, 0xb8, 0x05, 0x2b, 0xe2, 0xac, 0xa0, 0xea, 0xf0, 0x5b,
	0x23, 0xca, 0x3e, 0xa0, 0xb4, 0xf2, 0x12, 0xe5, 0x75, 0x81, 0xa4, 0xf3, 0x32, 0x5e, 0x30, 0x6c,
	0x30, 0x26, 0xa8, 0x3d, 0x1b, 0xcc, 0xad, 0xe0, 0xf4, 0xd5, 0x25, 0x98, 0xaa, 0x8c, 0x33, 0x06,
	0xf3, 0xe3, 0x6a, 0xf9, 0xe9, 0xe2, 0x89, 0x52, 0xd1, 0x92, 0xdc, 0x5d, 0x18, 0x21, 0x81, 0x69,
	0xc3, 0xea, 0x2d, 0xab, 0xef, 0x45, 0x25, 0xb9, 0x28, 0x9d, 0x2b, 0x5f, 0x3f, 0x82, 0xdf, 0x3f,
	0x82, 0x1f, 0xf1, 0x82, 0x2d, 0xf1, 0xb0, 0x71, 0x7f, 0xfc, 0xb1, 0x66, 0xa3, 0xf9, 0x64, 0x31,
	0xc5, 0x11, 0xfb, 0xa7, 0x20, 0xe7, 0x9a, 0xa1, 0xbf, 0x52, 0xcc, 0x07, 0x4e, 0x69, 0xc1, 0xee,
	0x33, 0x5e, 0x48, 0x56, 0x0f, 0x30, 0x7f, 0x1e, 0x61, 0x6a, 0x46, 0x84, 0x88, 0xf0, 0x2d, 0x58,
	0x19, 0x5e, 0xc8, 0xf5, 0x01, 0x16, 0x2b, 0xe8, 0xbf, 0x05, 0x8d, 0xf9, 0x64, 0x01, 0x08, 0xc3,
	0x23, 0xa2, 0x93, 0xe1, 0x2d, 0x58, 0x6b, 0xdc, 0x83, 0x97, 0x7b, 0x88, 0x15, 0xab, 0xb7, 0x3c,
	0x65, 0x87, 0x21, 0xb8, 0x3c, 0x44, 0x67, 0xc3, 0x15, 0x9c, 0xa3, 0xe8, 0x47, 0x1b, 0x64, 0x1d,
	0x99, 0x6e, 0x82, 0x94, 0x6e, 0xb8, 0x77, 0x60, 0xe7, 0x7a, 0xe1, 0x5e, 0xec, 0xe1, 0xee, 0x98,
	0xcc, 0xc5, 0xde, 0x78, 0x13, 0xa4, 0xe9, 0x2d, 0x25, 0x5d, 0x38, 0xfc, 0x02, 0x53, 0xad, 0xfa,
	0x72, 0x43, 0xb4, 0x63, 0x37, 0xaf, 0x29, 0xbb, 0x72, 0x8d, 0x5e, 0xde, 0x21, 0xdc, 0xaf, 0xff,
	0xca, 0xe9, 0x8d, 0x27, 0x5d, 0x58, 0x95, 0xd3, 0xea, 0xd4, 0x72, 0xbf, 0x8f, 0xad, 0x1a, 0x52,
	0x74, 0xb9, 0x1b, 0xf7, 0xeb, 0xf3, 0xc3, 0x7f, 0x2b, 0x89, 0x8d, 0xd8, 0x37, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x1e, 0xa6, 0xd0, 0xa8, 0x77, 0x04, 0x00, 0x00,
}
